Error handling for wrapper - client - server call mismatches
cloudera-labs/cdpy pull request #25
Opened 2021-07-26 11:01 UTC by Chaffelson

Add error handling for when the user requests a call from cdpy that is not available in the installed CDPCLI
Add error handling for when CDPCLI makes a call that is not available in the remote CDP Control Plane

Signed-off-by: Daniel Chaffelson <chaffelson@gmail.com>

2021-07-26 11:03 UTC, Chaffelson commented
@wmudge @cmperro I implemented this to handle the possibility of version mismatches between CDPCLI and CDP Control Plane, both now with the new DF API, but also in consideration of Private Cloud versions in future.
I'm not sure we *need* it however - it's just a better catch and release on the error, which means we could code responses, but I think actually we'd probably still want the Play to halt in these situations as the user is almost certainly not expecting it. Thoughts?

2021-09-16 13:09 UTC, wmudge commented
@Chaffelson -- has conflicts that need resolution.

2021-09-16 13:10 UTC, wmudge requested changes
LGTM, but GH is complaining about conflicts from upstream. Rebase and resolve?

2021-10-05 20:50 UTC, wmudge approved these changes

2021-10-05 20:52 UTC, merged